In [5]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18], 
          [19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 34, 35]])

print(a.shape)
print(a)
# numpy is 0 indexed

(6, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 34 35]]


In [9]:
take_row = a[1 : 5] # keep 1 to 4'th row
print(ex_row)

[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [10]:
take_col = a[:, 2 : 4] # keep 2nd to 3rd column
print(ex_col)

[[ 3  4]
 [ 9 10]
 [15 16]
 [21 22]
 [27 28]
 [33 34]]


In [12]:
take_row_col = a[1:5, 2 : 4] # keep 1 to 4 row and 2 to 3 col
print(take_row_col)

[[ 9 10]
 [15 16]
 [21 22]
 [27 28]]


In [20]:
# access i'th column
print(a[:,:1])  # 1's column
print(np.sum(a[:,:1]))

print(a[:,1:2]) # 2nd column
print(a[:,2:3]) # 3rd column

[[ 1]
 [ 7]
 [13]
 [19]
 [25]
 [31]]
96
[[ 2]
 [ 8]
 [14]
 [20]
 [26]
 [32]]
[[ 3]
 [ 9]
 [15]
 [21]
 [27]
 [33]]


In [32]:
print (a[:,[0]]) # 0 = col index
print (a[:,[1]]) # 1 = col index
print (a[:,[2]]) # 2 = col index

[[ 1]
 [ 7]
 [13]
 [19]
 [25]
 [31]]
[[ 2]
 [ 8]
 [14]
 [20]
 [26]
 [32]]
[[ 3]
 [ 9]
 [15]
 [21]
 [27]
 [33]]
